# Generated by Django 5.0.4 on 2024-06-13 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_bid_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comments",
            new_name="comment",
        ),
    ]
