# Generated by Django 5.0.4 on 2024-06-13 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_comments_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="comments",
            field=models.ManyToManyField(blank=True, to="auctions.comment"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
