# Generated by Django 5.0.4 on 2024-06-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="comments",
        ),
    ]
