# Generated by Django 5.0.4 on 2024-06-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comment_listings_alter_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
