# Generated by Django 5.0.4 on 2024-06-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="poster",
            field=models.CharField(default="Anonymous", max_length=64),
        ),
    ]
