# Generated by Django 5.0.4 on 2024-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_comment_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bids",
            field=models.ManyToManyField(
                blank=True, related_name="bids", to="auctions.listing"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="owner",
            field=models.CharField(default="Anonymous", max_length=64),
        ),
    ]
