# Generated by Django 5.0.4 on 2024-06-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_bid_bids_alter_bid_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="listing",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="listing",
            name="creator",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="bid",
            name="owner",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="comment",
            name="poster",
            field=models.CharField(max_length=64),
        ),
    ]
