# Generated by Django 5.0.4 on 2024-06-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_bid_listing_comment_listing_listing_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="listing",
            name="creator",
            field=models.CharField(max_length=64),
        ),
    ]
