# Generated by Django 5.0.4 on 2024-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_alter_bid_listing_alter_comment_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(default="active", max_length=64),
        ),
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.CharField(default="", max_length=64),
        ),
    ]
