# Generated by Django 5.0.4 on 2024-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_listing_status_listing_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="winner",
            field=models.CharField(default="None", max_length=64),
        ),
    ]
