# Generated by Django 5.0.4 on 2024-07-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_listing_winner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="auctions.category"
            ),
        ),
    ]
